/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dinasour;

import java.util.ArrayList;

public class App {
    public String getGreeting(){
        return "hellooo";
    }


    public static void main(String[] args) {
      
    }

    public static boolean search(ArrayList<Integer> array,int e){
        System.out.println("inside search");

        if(array==null){
            return false;
        }

        for(int elt:array){
            if(elt==e)
             return true;
        }
        return false;
    }

}
